### ISSUE TITLE
Adb get_devices doesn't work on Windows

### ISSUE THREAD

**Issue by radu-savutiu-deindeal** [archpoint/pyand#3]
get_devices doesn't work, it returns an empty dictionary.
If I use adb.run_cmd("devices"), then it works.

This only happens on a Windows Machine, on my Mac it works.

Found out the problem was that the output from adb uses \r for line ending while the pyand library separates the list with \n

**Comment by radu-savutiu-deindeal** [comment]
Here is my rewrited function:


```
def get_devices(self):
        """
        Return a dictionary of connected devices along with an incremented Id.
        adb devices
        """
        error = 0
        #Clear existing list of devices
        self.__devices = None
        self.run_cmd("devices")
        print "Output:", self.__output
        device_dict =  {}
        if self.__error is not None:
            return None
        try:
            n = 0
            output_list = self.__output.split("\n")
            for line in output_list:
                pattern = re.compile(r"([^\s]+)\s+device$")
                device = pattern.findall(line)
                print device
                if device:
                    device_dict[n] = device[0]
                    n += 1
                #endif
            if len(device_dict)==0:
                print "device list quickfix \r"
                output_list = self.__output.split("\r")
                print "output list:", output_list
                for line in output_list:
                    print "line: ", line, type(line)
                    pattern = re.compile(r"([^\s]+)\s+device$")
                    device = pattern.findall(line)
                    print device
                    if device:
                        print "device found: ", device
                        device_dict[n] = device[0]
                        n += 1
                        # endif
        except:
            self.__devices = None
            error = 1
        self.__devices = device_dict
        return self.__devices
```

**Comment by Zyg0te** [comment]
Thanks for reporting this. I didnt really test anything on Windows at all so Windows-related issues were bound to exist. 

Ill verify your change and commit it. Alternatively, you can create a pull request. 

Cheers

**Comment by radu-savutiu-deindeal** [comment]
I did a pull request, please have a look:

https://github.com/Zyg0te/pyand/pull/4

**Comment by SacrilegeTx** [comment]
Can u add this for windows, I really love this library and need the change for my script.

**import platform**

def get_devices(self):
        """
        Return a dictionary of connected devices along with an incremented Id.
        adb devices
        """
        error = 0
        #Clear existing list of devices
        self.__devices = None
        self.run_cmd("devices")
        print "Output:", self.__output
        device_dict =  {}
        if self.__error is not None:
            return None
        try:
            n = 0
            **if platform.system().lower() != "windows":
                output_list = self.__output.split("\n")
            else:
                output_list = self.__output.split("\r")**
            for line in output_list:
                pattern = re.compile(r"([^\s]+)\s+device$")
                device = pattern.findall(line)
                print device
                if device:
                    device_dict[n] = device[0]
                    n += 1
        except:
            self.__devices = None
            error = 1
        self.__devices = device_dict
        return self.__devices

**Comment by archpoint** [comment]
@SacrilegeTx Thanks for the feedback and apologies for the late response. Ive committed a fix for this and will be merging it now. Hope it works.
